const rows = [
    {
        id: 1,
        name: "Jon Snow",
        designation: "Professor",
        qualification: "PhD in History",
        image: "https://t3.ftcdn.net/jpg/02/43/12/34/360_F_243123463_zTooub557xEWABDLk0jJklDyLSGl2jrr.jpg",
    },
    {
        id: 2,
        name: "Cersei Lannister",
        designation: "Lecturer",
        qualification: "Masters in Political Science",
        image: "https://cdn2.psychologytoday.com/assets/styles/manual_crop_1_91_1_1528x800/public/field_blog_entry_images/2018-09/shutterstock_648907024.jpg?itok=7lrLYx-B",
    },
    {
        id: 3,
        name: "Daenerys Targaryen",
        designation: "Assistant Professor",
        qualification: "Masters in International Relations",
        image: "https://cdn2.psychologytoday.com/assets/styles/manual_crop_1_91_1_1528x800/public/field_blog_entry_images/2018-09/shutterstock_648907024.jpg?itok=7lrLYx-B",
    },
    {
        id: 4,
        name: "Tyrion Lannister",
        designation: "Senior Lecturer",
        qualification: "PhD in Political Economy",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmCicxernIb5W2jIRbjKwiMOVIit_7XJtczA&s",
    },
    {
        id: 5,
        name: "Arya Stark",
        designation: "Research Associate",
        qualification: "Masters in Sociology",
        image: "https://t3.ftcdn.net/jpg/03/02/88/46/360_F_302884605_actpipOdPOQHDTnFtp4zg4RtlWzhOASp.jpg",
    },
    {
        id: 6,
        name: "Bran Stark",
        designation: "Lecturer",
        qualification: "Masters in Philosophy",
        image: "https://t3.ftcdn.net/jpg/03/02/88/46/360_F_302884605_actpipOdPOQHDTnFtp4zg4RtlWzhOASp.jpg",
    },
    {
        id: 7,
        name: "Sansa Stark",
        designation: "Adjunct Professor",
        qualification: "Masters in Political Science",
        image: "https://t4.ftcdn.net/jpg/03/83/25/83/360_F_383258331_D8imaEMl8Q3lf7EKU2Pi78Cn0R7KkW9o.jpg",
    },
    {
        id: 8,
        name: "Jaime Lannister",
        designation: "Lecturer",
        qualification: "Masters in Military History",
        image: "https://t4.ftcdn.net/jpg/03/83/25/83/360_F_383258331_D8imaEMl8Q3lf7EKU2Pi78Cn0R7KkW9o.jpg",
    },
    {
        id: 9,
        name: "Samwell Tarly",
        designation: "Research Fellow",
        qualification: "PhD in Library Science",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjmRajktmioyiuB0RSaoQevXCCH-T5Qdt_dA&s",
    },
    {
        id: 10,
        name: "Jorah Mormont",
        designation: "Assistant Lecturer",
        qualification: "Masters in Ethics",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjmRajktmioyiuB0RSaoQevXCCH-T5Qdt_dA&s",
    },
    {
        id: 11,
        name: "Sandor Clegane",
        designation: "Instructor",
        qualification: "Masters in Physical Education",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjmRajktmioyiuB0RSaoQevXCCH-T5Qdt_dA&s",
    },
    {
        id: 12,
        name: "Brienne of Tarth",
        designation: "Lecturer",
        qualification: "Masters in Gender Studies",
        image: "https://img.freepik.com/free-photo/happiness-wellbeing-confidence-concept-cheerful-attractive-african-american-woman-curly-haircut-cross-arms-chest-self-assured-powerful-pose-smiling-determined-wear-yellow-sweater_176420-35063.jpg",
    },
    {
        id: 13,
        name: "Stannis Baratheon",
        designation: "Professor",
        qualification: "PhD in Law",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyzTWQoCUbRNdiyorem5Qp1zYYhpliR9q0Bw&s",
    },
    {
        id: 14,
        name: "Melisandre",
        designation: "Senior Lecturer",
        qualification: "PhD in Theology",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyzTWQoCUbRNdiyorem5Qp1zYYhpliR9q0Bw&s",
    },
    {
        id: 15,
        name: "Robert Baratheon",
        designation: "Adjunct Lecturer",
        qualification: "Masters in Political Science",
        image: "https://media.istockphoto.com/id/1454192305/photo/portrait-of-a-handsome-young-businessman-in-the-office.jpg?b=1&s=170667a&w=0&k=20&c=2U5pnYBD4IuQrCXcvy4gDk4HL_pHVTAxLNHGPrRMlLs=",
    },
    {
        id: 16,
        name: "Renly Baratheon",
        designation: "Lecturer",
        qualification: "Masters in Public Administration",
        image: "https://media.istockphoto.com/id/1279844456/photo/young-indian-business-woman-entrepreneur-looking-at-camera-in-the-office.webp?b=1&s=170667a&w=0&k=20&c=yFtE_NkazT64oWCk4hPdlLAzZ_iWJBEsi-KjV-0OS2s=",
    },
    {
        id: 17,
        name: "Petyr Baelish",
        designation: "Senior Lecturer",
        qualification: "PhD in Economics",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVI8wwjmbk07RHjMaoxGcLQw5kRfAizckn7g&s",
    },
    {
        id: 18,
        name: "Varys",
        designation: "Research Scholar",
        qualification: "Masters in International Affairs",
        image: "https://media.istockphoto.com/id/1368076322/photo/portrait-of-a-confident-businesswoman-in-an-office.webp?b=1&s=170667a&w=0&k=20&c=sMc2g5vzwaZG72TNUsiaiB05Uwoa0FcipI_KSGpT8VA=",
    },
    {
        id: 19,
        name: "Eddard Stark",
        designation: "Professor",
        qualification: "PhD in Law",
        image: "https://media.istockphoto.com/id/2159817925/photo/portrait-of-modern-businesswoman.webp?b=1&s=170667a&w=0&k=20&c=GiToSgPGlPjY9vFkjDsamP7ZGbrG5iV3tLtZNx2jOko=",
    },
    {
        id: 20,
        name: "Robb Stark",
        designation: "Assistant Professor",
        qualification: "Masters in Political Science",
        image: "https://media.istockphoto.com/id/2159817925/photo/portrait-of-modern-businesswoman.webp?b=1&s=170667a&w=0&k=20&c=GiToSgPGlPjY9vFkjDsamP7ZGbrG5iV3tLtZNx2jOko=",
    },
];

export default rows;